# See http://www.appveyor.com/docs/appveyor-yml for many more options
os: WMF 5

install:
  - cinst pester

build: false

test_script:
  - ps: . .\build.ps1

# Skip on updates to the readme.
skip_commits:
  message: /updated readme.*|update readme.*s/
